version: '2'
services:
  ropensciplumber:
    build: ./app/
    volumes:
     - ./app:/app
    network_mode: bridge
    restart: always
    ports:
     - "8073:8000"
    command: /app/plumber.R
    labels:
    - traefik.enable=false